### PR TITLE
Add command that find plans that match a ClusterServiceClass

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #49

### CODE REVIEW

**Comment by geoand** [comment]
@cmoulliard The implementation is feature complete, but if you can please test it, then we can merge it later if you think it fits out needs

**Comment by geoand** [comment]
plans

**Comment by cmoulliard** [comment]
I did a test and, for the moment, I don't see improvements required. WDYT @iocanel @metacosm ?

**Comment by cmoulliard** [comment]
@geoand Is a table the most appropriate format to display such info. Why this remark : As the parameters will most probably be added manually or by the tool within the MANIFEST file (=> should be renamed to application.yaml file maybe), then YAML output format is more appropriate to copy/paste the content within the file of the application that we are using to create the service

**Comment by geoand** [comment]
@cmoulliard Currently all our output is human readable, not machine readable.
I agree that we need to give the option to create output in yaml that will then be used by this or other tools. However I believe it's out of scope of this PR and should be dealt with in subsequent PRs

**Comment by metacosm** [comment]
@cmoulliard should I merge?

**Comment by metacosm** [comment]
Created an issue to track the `MANIFEST` rename: #51

**Comment by cmoulliard** [comment]
You can merge @metacosm. I will create a separate issue to keep track about different output formats

**Comment by geoand** [comment]
I will merge it, thanks

**Pull request merged**
